schedules:
  commit:
    # Run short and medium suites on commit
    schedule: per_commit
    matrix:
      exclude:
        - cassandra: ['dse-5.0', 'dse-5.1']
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (1.1, 1.x, 1.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
  adhoc:
    # Adhoc job for non-primary branches that doesn't have a schedule but may be used to run all configs.
    schedule: adhoc
    branches:
      exclude: ["/\\d+(\\.[\\dx]+)+/"]
java:
  - openjdk8
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - 2.2
  - 3.0
  - 3.11
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
  - dse-6.8
  - ddac-5.1
build:
  - type: maven
    version: 3.2.5
    goals: verify -Pmedium --fail-never -B
    properties: |
      com.datastax.dsbulk.commons.tests.ccm.CCM_VERSION=$CCM_VERSION
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DDAC=$CCM_IS_DDAC
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DSE=$CCM_IS_DSE
      com.datastax.dsbulk.commons.tests.ccm.JAVA_HOME=$CCM_JAVA_HOME
      com.datastax.dsbulk.commons.tests.ccm.PATH=$CCM_JAVA_HOME/bin
      com.datastax.dsbulk.commons.tests.cloud.PROXY_PATH=$HOME/proxy
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      max.simulacron.clusters=2
      max.ccm.clusters=1
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco:
    exec_pattern: "**/target/**.exec"
    exclusion_pattern: "com/datastax/kafkaconnector/schema/Mapping*"
