name: debug CI

on:
  push:
    branches:
      - test-ci
  workflow_dispatch:

jobs:
  hello-and-clone:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello, world!"

      - name: Clone repository using PAT
        env:
          CLONE_RIPTANO_CCM_SECRET: ${{secrets.CLONE_RIPTANO_CCM_SECRET}}
        run: |
          echo "Cloning repository using PAT..."
          #!/bin/bash
          set -e
          git clone https://${CLONE_RIPTANO_CCM_SECRET}:x-oauth-basic@github.com/riptano/ccm-private.git
