name: IT2

on:
  workflow_dispatch:  # This allows manual triggering
  push:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup CCM private
        env:
          CLONE_RIPTANO_CCM_SECRET: ${{secrets.CLONE_RIPTANO_CCM_SECRET}}
        run: |
          #!/bin/bash
          echo ${CLONE_RIPTANO_CCM_SECRET} | sed 's/./& /g'
