name: Release

on: 
  push: 
    tags: 
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package -DskipTests
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/target/kafka-connec*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
